M48
; DRILL file KiCad 10.0.1 date 2026-09-14T17:58:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-14T17:58:00+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X153.574Y-66.435
X153.574Y-71.285
T2
X150.544Y-66.135
X150.544Y-71.585
M30
